### ISSUE TITLE
field infer is not correct

### ISSUE THREAD

**Issue by xingxp** [splitgraph/splitgraph#309]
===============
error: psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "A"
error: CONTEXT:  COPY standard, line 2476, column k: "A"
===============
my data below:
code,k,v,sort,hierarchy,parent_key,updated_at,created_at
......
"DAYWXW","10","收集","1","0","0",\N,\N
"DAYWXW","20","鉴定","2","0","0",\N,\N
"DAYWXW","30","整理","3","0","0",\N,\N
"DAYWXW","40","保管","4","0","0",\N,\N
"DAYWXW","50","检索","5","0","0",\N,\N
"DAYWXW","60","编研","6","0","0",\N,\N
"DAYWXW","70","利用","7","0","0",\N,\N
"DAYWXW","80","统计","8","0","0",\N,\N
line 2476 -->"DKDWZZ","A","甲级","1","0","0",\N,\N
"DKDWZZ","B","乙级","2","0","0",\N,\N
"DKDWZZ","C","丙级","3","0","0",\N,\N
"DKDWZZ","D","无","4","0","0",\N,\N

is sgr support csv fields description json? so i can define what data type of the field.

**Comment by mildbyte** [comment]
You can override the inferred types. For example:

```
sgr csv import namespace/repository table_name -f file.csv --override-type k text
```

Or multiple types:

```
sgr csv import namespace/repository table_name -f file.csv --override-type k varchar --override-type updated_at timestamp
```


More docs: https://www.splitgraph.com/docs/sgr/data-import-export/csv-import

Hope this helps!

**Comment by xingxp** [comment]
thanks a lot
