### ISSUE TITLE
Splitfile build error - error: NotImplementedError: Printer for node 'TableLikeClause' is not implemented yet

### ISSUE THREAD

**Issue by mingfang** [splitgraph/splitgraph#525]
I'm running the splitfile below after `sgr csv import <source file>`.

```
FROM ${REPOSITORY}

SQL {
    CREATE TABLE IF NOT EXISTS ${TABLE}
    (LIKE "${SOURCE}".${TABLE}
    INCLUDING ALL)
}
```

But it's printing the error below.
```
error: NotImplementedError: Printer for node 'TableLikeClause' is not implemented yet
```

I'm using this CTA syntax to automatically copy the source primary index, which I'm hoping was created by
```
sgr csv import --primary-key my_key
```

**Comment by mildbyte** [comment]
https://github.com/splitgraph/splitgraph/pull/534 should fix it (newer pglast has support for printing the new PG statements that we use to get a consistent Splitfile image hash):

```python
from pglast import parse_sql, Node
from pglast.stream import IndentedStream
n = Node(parse_sql("CREATE TABLE a (LIKE b INCLUDING ALL)"))
print(str(IndentedStream()(n)))

CREATE TABLE a (
  LIKE b INCLUDING ALL
)
```

**Comment by mingfang** [comment]
Would it be possible to do a pip release to include this fix?

**Comment by mildbyte** [comment]
We'll do that soon-ish to include https://github.com/splitgraph/splitgraph/pull/550 and dependency bumps too.
