### ISSUE TITLE
Configuration file requires write access

### ISSUE THREAD

**Issue by harrybiddle** [splitgraph/splitgraph#653]
I wish to use Splitgraph on a JupyterHub instance. I'd like to provide all users with the same configuration. So I created a file at /etc/xdg/splitgraph/sgconfig.ini and set the SG_CONFIG_FILE environment variable to point to this.

However, Splitgraph requires write access to this file. That's a bit odd for a system-wide configuration file! Would it be possible for Splitgraph to write to the user file rather than the system one? Or is this kind of system-wide configuration just not supported/recommended?

```
/opt/tljh/user/lib/python3.6/site-packages/splitgraph/cloud/__init__.py in access_token(self)
    519 
    520         set_in_subsection(config, "remotes", self.remote, "SG_CLOUD_ACCESS_TOKEN", new_access_token)
--> 521         overwrite_config(config, get_singleton(config, "SG_CONFIG_FILE"))
    522         return new_access_token
    523 

/opt/tljh/user/lib/python3.6/site-packages/splitgraph/config/export.py in overwrite_config(new_config, config_path, include_defaults)
    105         new_config, config_format=True, no_shielding=True, include_defaults=include_defaults
    106     )
--> 107     with open(config_path, "w") as f:
    108         f.write(new_config_data)

PermissionError: [Errno 13] Permission denied: '/etc/xdg/splitgraph/sgconfig.ini'
```

**Comment by mildbyte** [comment]
Yeah, it stores the access token in the config file (as well as a couple other things, like the timestamp of the last "new version available" message).

Are you using the sgr CLI on Jupyter Cloud or calling the GQLAPIClient/RESTAPIClient from your code? In the latter case, the token stays in the memory so there's no need to flush it to the config file until it expires and we could disable that.

**Comment by mildbyte** [comment]
Could this work? https://github.com/splitgraph/splitgraph/commit/435f769f40d9

**Comment by harrybiddle** [comment]
> Are you using the sgr CLI on Jupyter Cloud or calling the GQLAPIClient/RESTAPIClient from your code? In the latter case, the token stays in the memory so there's no need to flush it to the config file until it expires and we could disable that.

The latter 👍 . aa8fa3b3b57530a6b0028a98a03caf76dddfa41b looks perfect, I'll give that a go

**Comment by mildbyte** [comment]
Nice! Let me know if it works for you and I'll merge it in.

**Comment by harrybiddle** [comment]
I just gave this a go, removing write permission from the Splitgraph config and confirming error without read_only mode but success with read_only mode. LGTM 👍
